### PR TITLE
Empowerment Balance try 2

### PR DESCRIPTION
**Pull request by Hornsoup**
People have already hit cap. Too late to take it back and too late to balance but this exists.

### CODE REVIEW

**Comment by immortalityidle** [comment]
Not sure what this math does, but it looks fancy. We should probably make a corresponding change to where we show the value in the ascension panel too though.

**Comment by Hornsoup** [comment]
Math just sets x10 to about a day and shoots the rest out to the sky so people can prove me wrong in how quickly they can farm it with the new time dilation. I'm still kinda working on bits, but I'll also add in the resultant value in ascension alongside pill count. I also reduced cap to 100 because it was just insane to have people with a 10k stat mult after grinding spirituality for a bit and dilating time with their insane age, it compounds.

**Comment by Hornsoup** [comment]
It's untested due to time constraints but the math checks out.

**Comment by ChandlerFerry** [comment]
Personal opinion is that this game needs a balance sweep as a whole as it's difficult to commit to playing with everything fluctuating so heavily.

The numbers just don't quite make sense in a lot of cases, but I don't have the necessary experience to say exactly what they should be.

**Review by ChandlerFerry — APPROVED** [review]
Code looks good.

Balance is TBD by someone else.

**Comment by Hornsoup** [comment]
Problem with balance is that there was none on release, it wasn't tested end-to-end so at the start Christian was patching for people to get through content. The early game is solid, but it's around 4/1/3 that things got bad and every fix thereafter has been damage control, sometimes damage.

**Pull request merged**
