### PR TITLE
Health panel progress bars

### PR DESCRIPTION
**Pull request by Ch1pless**
Swapped progress element for a more generic but cross platform div and span combo.

### CODE REVIEW

**Comment by immortalityidle** [comment]
I like this. We should probably do this all over where we use progress elements. Want to move the style stuff into the styles.less file so we don't have to replicate it in all the component less files?

**Comment by Ch1pless** [comment]
Yes I can do so, I'll do that some point today. Do you think making the text display "value / max" would be something to do too? Or leave it as "value"?

**Comment by Ch1pless** [comment]
Also, should I apply the Math.floor to all display values considering the recent bug on the discord?

**Comment by Kleptichron** [comment]
I think having max would be preferable from a player standpoint. There's plenty of times where stamina or mana are just hovering at the bottom of the range and the max isn't visible anywhere else.

**Comment by immortalityidle** [comment]
I think the nutrition bar might still have issues in dark mode, white text on yellow. If you flip to light mode does the dark text show up on the dark background? or does the background of the widget flip with the mode?

**Comment by immortalityidle** [comment]
I'm also not married to the nutrition color. If it makes your life easier to change that, that's fine.

**Comment by Ch1pless** [comment]
the modification to app.component.less was spacing formatted (some css classes had a 2 space indent, others had a 4 space one)

**Comment by Ch1pless** [comment]
Just to make sure Credit to  @Coebh for the gradient backgrounded text on the progress bars.

**Review by immortalityidle — APPROVED** [review]
So excited to test this out.

**Pull request merged**
