### PR TITLE
Optimising followers

### PR DESCRIPTION
**Pull request by kagejohn**
I found that these 3 follower types caused lag: farmer, hunter, scout.
I have fixed farmer and hunter.
Scout is fixed in #124 

At the same time i found a bug with field.yield.

### CODE REVIEW

**Comment by immortalityidle** [comment]
This is much better than what I put in.

**Comment by kagejohn** [comment]
That should be all of the places where a follower is updated in some way

**Review by immortalityidle — APPROVED** [review]

**Comment by immortalityidle** [comment]
Oh, one more should probably call the set total power function at the bottom of setProperties.

**Comment by kagejohn** [comment]
Yeah, i noticed that followers didn't do anything on page load, so i panicked.
Thanks for the location.

**Pull request merged**
